[package]
name = "vending_machines_nostr"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-sdk = { version = "0.41.0", features = ["nip44"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
